### ISSUE TITLE
run the python calc_CORL2017_Tables.py , i meet some problem

### ISSUE THREAD

**Issue by Warsin** [mvpcom/carlaILTrainer#14]
hello,when i run the example: python calc_CORL2017_Tables.py --path "./_benchmarks_results/test/" -v -n "CoRL-2017 Carla Paper ,  i meet this error :"No such file or directory: './CarlaPaper_ReExperiment/CarlaPaperModel_Test02_CoRL2017_Town01_Test01_CoRL2017_Town01/summary.csv',Can you please help?
Thanks a lot!

**Comment by mvpcom** [comment]
Hi @Warsin, Sorry for the late answer. I hope you already fixed your problem. For your mentioned problem, you have first to run the benchmark, and after that, you will have those required files for generating a table like Carla paper.
