### ISSUE TITLE
Another training code implementation for Conditional Imitation Learning

### ISSUE THREAD

**Issue by markus-hinsche** [mvpcom/carlaILTrainer#16]
Hi @mvpcom! We wrote an implementation (https://github.com/merantix/imitation-learning), it aims to achieve a similar objective as this repository, namely: Provide training code for Conditional Imitation Learning.

This repository was a great help. Thanks @mvpcom!

Would be nice to exchange about our learnings? Maybe you have some feedback: Have a look if you like.

**Comment by mvpcom** [comment]
Thank you so much @markus-hinsche and thank you for sharing your code to the public. I'm happy it was useful for you. And, sorry for the late answer.
