### ISSUE TITLE
Dropout Vector

### ISSUE THREAD

**Issue by nelsoonc** [mvpcom/carlaILTrainer#20]
Hello @mvpcom, I want to ask about the dropout vector. In the code, the dropout vector seems to have 1.0 and 0.7 value when in the imitation-learning paper stated 50% dropout after fully connected layers and 20% dropout after convolutional layer. Or am I missing something here? Thank you

**Comment by mvpcom** [comment]
@nelsoonc Hi, I am suggesting using the official [repo](https://github.com/felipecode/coiltraine). This was only an initial attempt to reproduce their results before they publish the code.

**Comment by nelsoonc** [comment]
Thank you for your reply !
