### ISSUE TITLE
Where to find the train and validation data set used for training purposes ?...(train.py)

### ISSUE THREAD

**Issue by soham2017** [mvpcom/carlaILTrainer#4]

**Comment by mvpcom** [comment]
[The dataset can be downloaded here](https://drive.google.com/file/d/1hloAeyamYn-H6MfV1dRtY1gJPhkR55sY/view). Check this [link](https://github.com/carla-simulator/imitation-learning) to find out more information.

**Comment by soham2017** [comment]
Thank you for your help.
