### ISSUE TITLE
Bad car performance in CARLA

### ISSUE THREAD

**Issue by Kabnoory** [mvpcom/carlaILTrainer#5]
Hey @mvpcom 

Thank you so much for the code it was very helpful! However, when I try to test the model in CARLA, I get bad results. Have you tried testing the trained model in CARLA? and if you did how were the results? what I found is that when the car doesn't move a lot of the trials or it misses the turns.

Do you have any suggestions I can do that might improve the model?

Thank you.

**Comment by mvpcom** [comment]
Hey @Kabnoory, for the part that the car doesn't move a lot and it will stop so many times, you can solve it a little bit. However, the main reason is the unbalanced dataset. You have to edit the code and balanced the samples. Currently, the zeros are the significant samples in the data, and you have to adjust on the air when you train the model. Besides that, use the latest version of CARLA and imitation learning code and use this command: "python run_CIL.py -c Town01 -n Model_Test01" without --avoid-stopping. Make sure it will avoid stopping utilizing the speed branch prediction. This will not solve the problem of unbalanced samples. However, for the second part of your question, this is not the final code. There is some TODOs which you can do. Check the main README.

**Comment by Kabnoory** [comment]
Thank you!
