### ISSUE TITLE
the predicted gas is so small

### ISSUE THREAD

**Issue by margonotmango** [mvpcom/carlaILTrainer#7]
hi,
I trained a model and use this to test, but the predicted throttle is so small, and the speed of the car is so small. Why this happen?

**Comment by mvpcom** [comment]
@margonotmango Hey, this means that your model didn't learning anything at least for the throttle. What about the other predictions? What is the final loss? which code you utilized in this repo to train the model? And, if you check the TODO, you will find out you have to make some minor changes to make everything work like a charm. I believe those TODOs are necessary for converging to a very good model.

**Comment by Warsin** [comment]
hi, i have also met this problem, the loss is  3.53621,do you have solved this problem?

**Comment by margonotmango** [comment]
> hi, i have also met this problem, the loss is 3.53621,do you have solved this problem?

Hi, I re-collected my data so that the value distribution of gas is similar to the numerical distribution of carla

**Comment by margonotmango** [comment]
@Warsin 
Hi, I re-collected my data so that the value distribution of gas is similar to the numerical distribution of carla
