### ISSUE TITLE
How to run the trained Model in Carla?

### ISSUE THREAD

**Issue by sayanmandal** [mvpcom/carlaILTrainer#9]
Hi,
   I have trained a model using your train.py, but can't figure out how to run the same model in Carla? Can you please help.

**Comment by sayanmandal** [comment]
when I run "python run_CIL.py" I get this: Key Network/Branch_0/Variable not found in checkpoint

**Comment by chowkamlee81** [comment]
@sayanmandal , can you tell us the code to do inference... Do the needful
